version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /febs/prometheus/:/etc/prometheus/
    ports:
      - 8403:9090
    restart: on-failure
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - 8405:9100
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8407:8080
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - /febs/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 8406:9093
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 8404:3000